### ISSUE TITLE
Add table inside content tab

### ISSUE THREAD

**Issue by tescrihuela** [timvink/mkdocs-table-reader-plugin#19]
First thanks for the great work. I am a very beginner and i like these kind of plugins which enhances user experience.
I would like to know if there was a clue to load a csv file with read_csv inside a [content tab](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/) ?

I did not manage to work them together in my project. I tried to build a minimal reproducible example in [my github](https://github.com/tescrihuela/read_csv_inside_content_tabs) to reproduce what happens :
![image](https://user-images.githubusercontent.com/9462723/120313379-2a1af180-c2da-11eb-9c6b-ec7cc2dcbe13.png)

Thanks !

**Comment by timvink** [comment]
Kudos on the reproducable example! I will look into it once I find some time.

**Comment by timvink** [comment]
The root cause is that when the markdown table is inserted, the indentation is lost for any second rows:

![image](https://user-images.githubusercontent.com/5570380/122357999-83c72100-cf54-11eb-8ca8-1e17f2d0d05e.png)

I managed to update the regex and add the indentation if necessary. Released in `0.6`, so `pip install --upgrade` to try it out.

**Comment by timvink** [comment]
Some unit tests failing, will fix and deploy shortly..

**Comment by tescrihuela** [comment]
tried it out and it works like a charm ! 👏 Thanks @timvink 🙏
