### ISSUE TITLE
path to csv should maybe be not relative to the yml location ...

### ISSUE THREAD

**Issue by codegarden13** [timvink/mkdocs-table-reader-plugin#6]
*"This package tries to be as simple as possible for the user (hide any complexity from the user)"*

If a user defines docs_dir, it's a pain to set this relative path for the csv.

**Comment by timvink** [comment]
Hi! 

From the readme:

> Where the path is relative to the location of your project's mkdocs.yml file.

Can you elaborate on why it's a pain to set the relative path? I don't think I understand your use-case yet. A guess: you want to specify the path relative to your `docs_dir`, instead of your `mkdocs.yml` ?

In my case, the csv's are in a `data/` folder in the root directory. If you're putting the csv's in the `docs/` folder, I can image it's a bit verbose to specify the path to the docs folder for every `{{ read_csv(path) }}`.

Any ideas on how to improve this behaviour? Perhaps add a setting (true/false) to use the path relative to the `docs_dir` instead of the `mkdocs.yml` file?

**Comment by codegarden13** [comment]
Hi Tim,

I think you understood the problem. 
Your guess is right - and I want to keep my csv files INSIDE my docs_dir. 
And I am a user - I tried around and did not find the way to specify a working path.

The true/false setting could be the right way (I am not a developer in python).

Maybe a path setting (relative to where) would be more universal.

But True/false would do the job. 

OR the option to declarate the location like { read_csv(abspath) } where the document could be anywhere ?

Kind regards and thank you for your work !

Thomas

**Comment by timvink** [comment]
Yes probably specifying a path would give the most flexibility, f.e. by adding a `data_path` option. I'll work on this for a next release, but low prio for me currently.

`{{ read_csv(abspath) }}` should already work btw.

**Comment by timvink** [comment]
Hi @codegarden13 ,

I just released [v0.4](https://github.com/timvink/mkdocs-table-reader-plugin/releases/tag/v0.4), let me know if this fixes the issue for you!
