### ISSUE TITLE
output of float values

### ISSUE THREAD

**Issue by PlasmaHH** [timvink/mkdocs-table-reader-plugin#65]
Hi, not sure if this is documented somewhere and I just missed it, but I can't seem to find a way to output float values with higher precision (Using read_csv if that matters)? E.g. I have nanosecond accurate seconds since epoch and those are all displayed as e.g. 1.71387e+09 which makes all of the digits quite useless...

PS: Is it possible that you cannot use this plugin within tabs, admonitions, blockquotes etc. as it will not pick up the indentation and start all but the first line at the beginning?

**Comment by timvink** [comment]
after reading the table, the dataframe is passed to `tabulate` in order to create the markdown table.

See  https://github.com/astanin/python-tabulate?tab=readme-ov-file#number-formatting

So you can try something like `{{ read_csv(..., floatfmt=".4f") }}`

> PS: Is it possible that you cannot use this plugin within tabs, admonitions, blockquotes etc. as it will not pick up the indentation and start all but the first line at the beginning?

It should work withing tabs (that's how I use it). Please share a small reproducable example if you have problems.

**Comment by timvink** [comment]
Here are the docs on number formatting: https://timvink.github.io/mkdocs-table-reader-plugin/howto/customize_tables/#number-formatting

If you are using this plugin with `macros` plugin, you will need to add ` | add_indentation(spaces=4)`, see https://timvink.github.io/mkdocs-table-reader-plugin/howto/use_jinja2/#insert-tables-into-content-tabs 

If this doesn't fix it, feel free to reopen
